/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
  const advancedSearchPage: typeof import('./src/domains/search/router')['advancedSearchPage']
  const baseLayoutTemplateGridCols: typeof import('./vendors/design-system/utils/layoutTemplate')['baseLayoutTemplateGridCols']
  const booleanFormField: typeof import('./vendors/design-system/utils/formFields')['booleanFormField']
  const buttonVariants: typeof import('./vendors/design-system/components/ui/button/index')['buttonVariants']
  const cguPage: typeof import('./src/domains/edito/router')['cguPage']
  const checkLayoutTemplateGridCols: typeof import('./vendors/design-system/utils/layoutTemplate')['checkLayoutTemplateGridCols']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createExternalPromise: typeof import('./vendors/design-system/utils/createExternalPromise')['createExternalPromise']
  const createFetchDebounce: typeof import('./vendors/design-system/utils/debounce')['createFetchDebounce']
  const createFormField: typeof import('./vendors/design-system/composables/useFormBuilder/createFormField')['createFormField']
  const createLayoutTemplate: typeof import('./vendors/design-system/composables/useFormBuilder/templates/createLayoutTemplate')['createLayoutTemplate']
  const createPage: typeof import('./vendors/design-system/utils/createPage')['createPage']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const documentFolderPage: typeof import('./src/domains/user/router')['documentFolderPage']
  const documentInFolderPage: typeof import('./src/domains/user/router')['documentInFolderPage']
  const documentPage: typeof import('./src/domains/document/router')['documentPage']
  const effectScope: typeof import('vue')['effectScope']
  const formTemplate: typeof import('./vendors/design-system/utils/layoutTemplate')['formTemplate']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const homePage: typeof import('./src/domains/edito/router')['homePage']
  const horizonClient: typeof import('./src/lib/horizon/index')['horizonClient']
  const i18n: typeof import('./src/i18n/index')['i18n']
  const inject: typeof import('vue')['inject']
  const inlineFormTemplate: typeof import('./vendors/design-system/utils/layoutTemplate')['inlineFormTemplate']
  const isEven: typeof import('./src/utils/isEven')['isEven']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const multiComboBoxFormField: typeof import('./vendors/design-system/utils/formFields')['multiComboBoxFormField']
  const multiLayoutTemplateGridCols: typeof import('./vendors/design-system/utils/layoutTemplate')['multiLayoutTemplateGridCols']
  const nextTick: typeof import('vue')['nextTick']
  const notFoundPage: typeof import('./src/domains/edito/router')['notFoundPage']
  const notificationListPage: typeof import('./src/domains/notification/router')['notificationListPage']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const postCreatePage: typeof import('./src/domains/forum/router')['postCreatePage']
  const postListPage: typeof import('./src/domains/forum/router')['postListPage']
  const postPage: typeof import('./src/domains/forum/router')['postPage']
  const profilePage: typeof import('./src/domains/user/router')['profilePage']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const searchPageQuery: typeof import('./src/domains/search/router')['searchPageQuery']
  const selectFormField: typeof import('./vendors/design-system/utils/formFields')['selectFormField']
  const selectStringFormField: typeof import('./vendors/design-system/utils/formFields')['selectStringFormField']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const simpleSearchPage: typeof import('./src/domains/search/router')['simpleSearchPage']
  const textFormField: typeof import('./vendors/design-system/utils/formFields')['textFormField']
  const textLayoutTemplateGridCols: typeof import('./vendors/design-system/utils/layoutTemplate')['textLayoutTemplateGridCols']
  const textareaFormField: typeof import('./vendors/design-system/utils/formFields')['textareaFormField']
  const toArrayZodSchema: typeof import('./src/utils/toArrayZodSchema')['toArrayZodSchema']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unionSelectLessLayoutTemplate: typeof import('./vendors/design-system/utils/layoutTemplate')['unionSelectLessLayoutTemplate']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useBaseLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useBaseLayout')['useBaseLayout']
  const useCheckLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useCheckLayout')['useCheckLayout']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useEmptyLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useEmptyLayout')['useEmptyLayout']
  const useFormBuilder: typeof import('./vendors/design-system/composables/useFormBuilder/index')['useFormBuilder']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useId: typeof import('vue')['useId']
  const useLink: typeof import('vue-router')['useLink']
  const useLoader: typeof import('./src/composables/useLoader')['useLoader']
  const useLocalStorageItem: typeof import('./vendors/design-system/composables/useLocalStorageItem')['useLocalStorageItem']
  const useModel: typeof import('vue')['useModel']
  const useMultiFieldLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useMultiFieldLayout')['useMultiFieldLayout']
  const useProvide: typeof import('./vendors/design-system/composables/useProvide')['useProvide']
  const useRefHasChange: typeof import('./vendors/design-system/composables/useRefHasChange')['useRefHasChange']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useScroll: typeof import('./vendors/design-system/composables/useScroll')['useScroll']
  const useSlots: typeof import('vue')['useSlots']
  const useSmoothEnabled: typeof import('./vendors/design-system/composables/useSmoothEnabled')['useSmoothEnabled']
  const useSonner: typeof import('./vendors/design-system/composables/useSonner')['useSonner']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTextLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useTextLayout')['useTextLayout']
  const useUnionLayout: typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useUnionLayout')['useUnionLayout']
  const useValidationDialog: typeof import('./vendors/design-system/composables/useValidationDialog')['useValidationDialog']
  const useWindow: typeof import('./vendors/design-system/composables/useWindow')['useWindow']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const zod: typeof import('./src/lib/zod/index')['zod']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { HorizonClientRoute } from './src/lib/horizon/index'
  import('./src/lib/horizon/index')
  // @ts-ignore
  export type { FormFieldOptions } from './vendors/design-system/composables/useFormBuilder/createFormField'
  import('./vendors/design-system/composables/useFormBuilder/createFormField')
  // @ts-ignore
  export type { BaseProps, ExposedProperties, FormFieldParams, FormFieldInstance, FormField, GetGenericFormField } from './vendors/design-system/composables/useFormBuilder/formField'
  import('./vendors/design-system/composables/useFormBuilder/formField')
  // @ts-ignore
  export type { CheckLayoutOptions } from './vendors/design-system/composables/useFormBuilder/layouts/useCheckLayout'
  import('./vendors/design-system/composables/useFormBuilder/layouts/useCheckLayout')
  // @ts-ignore
  export type { MultiLayoutOptions } from './vendors/design-system/composables/useFormBuilder/layouts/useMultiFieldLayout'
  import('./vendors/design-system/composables/useFormBuilder/layouts/useMultiFieldLayout')
  // @ts-ignore
  export type { MaybeRef, FormContext, FormOptions } from './vendors/design-system/composables/useFormBuilder/index'
  import('./vendors/design-system/composables/useFormBuilder/index')
  // @ts-ignore
  export type { BaseLayoutOptions, MaybeCheckedType, ChouseDefaultValue } from './vendors/design-system/composables/useFormBuilder/layouts/useBaseLayout'
  import('./vendors/design-system/composables/useFormBuilder/layouts/useBaseLayout')
  // @ts-ignore
  export type { TextLayoutOptions } from './vendors/design-system/composables/useFormBuilder/layouts/useTextLayout'
  import('./vendors/design-system/composables/useFormBuilder/layouts/useTextLayout')
  // @ts-ignore
  export type { UnionLayoutOptions } from './vendors/design-system/composables/useFormBuilder/layouts/useUnionLayout'
  import('./vendors/design-system/composables/useFormBuilder/layouts/useUnionLayout')
  // @ts-ignore
  export type { BaseLayoutTemplateProps, BaseLayoutTemplateItem, BaseLayoutTemplateRender } from './vendors/design-system/composables/useFormBuilder/templates/baseLayout'
  import('./vendors/design-system/composables/useFormBuilder/templates/baseLayout')
  // @ts-ignore
  export type { CheckLayoutTemplateProps, CheckLayoutTemplateItem, CheckLayoutTemplateRender } from './vendors/design-system/composables/useFormBuilder/templates/checkLayout'
  import('./vendors/design-system/composables/useFormBuilder/templates/checkLayout')
  // @ts-ignore
  export type { LayoutTemplateItem, MaybeArray, TemplateSlotNode, TemplateRender, LayoutTemplateItems, FindLayoutTemplateItem } from './vendors/design-system/composables/useFormBuilder/templates/createLayoutTemplate'
  import('./vendors/design-system/composables/useFormBuilder/templates/createLayoutTemplate')
  // @ts-ignore
  export type { FormTemplateProps, FormTemplateRender, FormTemplateItem } from './vendors/design-system/composables/useFormBuilder/templates/form'
  import('./vendors/design-system/composables/useFormBuilder/templates/form')
  // @ts-ignore
  export type { MultiLayoutTemplateProps, MultiLayoutTemplateItem, MultiLayoutTemplateRender } from './vendors/design-system/composables/useFormBuilder/templates/multiLayout'
  import('./vendors/design-system/composables/useFormBuilder/templates/multiLayout')
  // @ts-ignore
  export type { TextLayoutTemplateProps, TextLayoutTemplateItem, TextLayoutTemplateRender } from './vendors/design-system/composables/useFormBuilder/templates/textLayout'
  import('./vendors/design-system/composables/useFormBuilder/templates/textLayout')
  // @ts-ignore
  export type { UnionLayoutTemplateProps, UnionLayoutTemplateItem, UnionLayoutTemplateRender } from './vendors/design-system/composables/useFormBuilder/templates/unionLayout'
  import('./vendors/design-system/composables/useFormBuilder/templates/unionLayout')
  // @ts-ignore
  export type { PageParams, PageGoParams, PageUse, Page } from './vendors/design-system/utils/createPage'
  import('./vendors/design-system/utils/createPage')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly advancedSearchPage: UnwrapRef<typeof import('./src/domains/search/router')['advancedSearchPage']>
    readonly baseLayoutTemplateGridCols: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['baseLayoutTemplateGridCols']>
    readonly booleanFormField: UnwrapRef<typeof import('./vendors/design-system/utils/formFields')['booleanFormField']>
    readonly cguPage: UnwrapRef<typeof import('./src/domains/edito/router')['cguPage']>
    readonly checkLayoutTemplateGridCols: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['checkLayoutTemplateGridCols']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createExternalPromise: UnwrapRef<typeof import('./vendors/design-system/utils/createExternalPromise')['createExternalPromise']>
    readonly createFetchDebounce: UnwrapRef<typeof import('./vendors/design-system/utils/debounce')['createFetchDebounce']>
    readonly createFormField: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/createFormField')['createFormField']>
    readonly createLayoutTemplate: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/templates/createLayoutTemplate')['createLayoutTemplate']>
    readonly createPage: UnwrapRef<typeof import('./vendors/design-system/utils/createPage')['createPage']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly documentPage: UnwrapRef<typeof import('./src/domains/document/router')['documentPage']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formTemplate: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['formTemplate']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly homePage: UnwrapRef<typeof import('./src/domains/edito/router')['homePage']>
    readonly horizonClient: UnwrapRef<typeof import('./src/lib/horizon/index')['horizonClient']>
    readonly i18n: UnwrapRef<typeof import('./src/i18n/index')['i18n']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly inlineFormTemplate: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['inlineFormTemplate']>
    readonly isEven: UnwrapRef<typeof import('./src/utils/isEven')['isEven']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly multiLayoutTemplateGridCols: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['multiLayoutTemplateGridCols']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly notFoundPage: UnwrapRef<typeof import('./src/domains/edito/router')['notFoundPage']>
    readonly notificationListPage: UnwrapRef<typeof import('./src/domains/notification/router')['notificationListPage']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly postCreatePage: UnwrapRef<typeof import('./src/domains/forum/router')['postCreatePage']>
    readonly postListPage: UnwrapRef<typeof import('./src/domains/forum/router')['postListPage']>
    readonly postPage: UnwrapRef<typeof import('./src/domains/forum/router')['postPage']>
    readonly profilePage: UnwrapRef<typeof import('./src/domains/user/router')['profilePage']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly searchPageQuery: UnwrapRef<typeof import('./src/domains/search/router')['searchPageQuery']>
    readonly selectFormField: UnwrapRef<typeof import('./vendors/design-system/utils/formFields')['selectFormField']>
    readonly selectStringFormField: UnwrapRef<typeof import('./vendors/design-system/utils/formFields')['selectStringFormField']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly simpleSearchPage: UnwrapRef<typeof import('./src/domains/search/router')['simpleSearchPage']>
    readonly textFormField: UnwrapRef<typeof import('./vendors/design-system/utils/formFields')['textFormField']>
    readonly textLayoutTemplateGridCols: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['textLayoutTemplateGridCols']>
    readonly textareaFormField: UnwrapRef<typeof import('./vendors/design-system/utils/formFields')['textareaFormField']>
    readonly toArrayZodSchema: UnwrapRef<typeof import('./src/utils/toArrayZodSchema')['toArrayZodSchema']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unionSelectLessLayoutTemplate: UnwrapRef<typeof import('./vendors/design-system/utils/layoutTemplate')['unionSelectLessLayoutTemplate']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBaseLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useBaseLayout')['useBaseLayout']>
    readonly useCheckLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useCheckLayout')['useCheckLayout']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useEmptyLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useEmptyLayout')['useEmptyLayout']>
    readonly useFormBuilder: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/index')['useFormBuilder']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLoader: UnwrapRef<typeof import('./src/composables/useLoader')['useLoader']>
    readonly useLocalStorageItem: UnwrapRef<typeof import('./vendors/design-system/composables/useLocalStorageItem')['useLocalStorageItem']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMultiFieldLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useMultiFieldLayout')['useMultiFieldLayout']>
    readonly useProvide: UnwrapRef<typeof import('./vendors/design-system/composables/useProvide')['useProvide']>
    readonly useRefHasChange: UnwrapRef<typeof import('./vendors/design-system/composables/useRefHasChange')['useRefHasChange']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useScroll: UnwrapRef<typeof import('./vendors/design-system/composables/useScroll')['useScroll']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSmoothEnabled: UnwrapRef<typeof import('./vendors/design-system/composables/useSmoothEnabled')['useSmoothEnabled']>
    readonly useSonner: UnwrapRef<typeof import('./vendors/design-system/composables/useSonner')['useSonner']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTextLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useTextLayout')['useTextLayout']>
    readonly useUnionLayout: UnwrapRef<typeof import('./vendors/design-system/composables/useFormBuilder/layouts/useUnionLayout')['useUnionLayout']>
    readonly useValidationDialog: UnwrapRef<typeof import('./vendors/design-system/composables/useValidationDialog')['useValidationDialog']>
    readonly useWindow: UnwrapRef<typeof import('./vendors/design-system/composables/useWindow')['useWindow']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly zod: UnwrapRef<typeof import('./src/lib/zod/index')['zod']>
  }
}