/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
	export interface GlobalComponents {
		DSAccordion: typeof import('./vendors/design-system/components/ui/accordion/DSAccordion.vue')['default']
		DSAccordionContent: typeof import('./vendors/design-system/components/ui/accordion/DSAccordionContent.vue')['default']
		DSAccordionItem: typeof import('./vendors/design-system/components/ui/accordion/DSAccordionItem.vue')['default']
		DSAccordionTrigger: typeof import('./vendors/design-system/components/ui/accordion/DSAccordionTrigger.vue')['default']
		DSButton: typeof import('./vendors/design-system/components/ui/button/DSButton.vue')['default']
		DSButtonOutline: typeof import('./vendors/design-system/components/DSButtonOutline.vue')['default']
		DSButtonPrimary: typeof import('./vendors/design-system/components/DSButtonPrimary.vue')['default']
		DSInput: typeof import('./vendors/design-system/components/ui/input/DSInput.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		TheFooter: typeof import('./src/components/TheFooter.vue')['default']
		TheHeader: typeof import('./src/components/TheHeader.vue')['default']
		TheLoader: typeof import('./src/components/TheLoader.vue')['default']
	}
}
