// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type AbstractSectionName = "introduction" | "background" | "objective" | "method" | "result" | "conclusion" | "reference" | "acknowledgment" | "objective" | "option" | "outcome" | "evidence" | "value" | "benefit" | "recommendation" | "validation" | "sponsor" | "purpose" | "patient" | "setting" | "studyObjective" | "measurementAndMainResult" | "introductions" | "backgrounds" | "objectives" | "methods" | "results" | "conclusions" | "references" | "acknowledgments" | "objectives" | "options" | "outcomes" | "evidences" | "values" | "benefits" | "recommendations" | "validations" | "sponsors" | "purposes" | "patients" | "settings" | "studyObjectives" | "measurementsAndMainResults";

export { AbstractSectionName };

type CodegenRoutes = ({
    method: "PUT";
    path: "/document/{language}";
    body: {
        abysBakedDocumentId: string;
        language: "fr-Fr" | "en-US";
        title: string;
        abstract: string | null;
        abstractDetails: Record<AbstractSectionName, {
            value: string;
        } | undefined> | null;
        ressources: {
            pubmed?: {
                name: string;
                url: string;
            } | undefined;
        };
        keywords: {
            value: string;
        }[];
        webPublishDate: Date | null;
        webPublishSplitDate: {
            day: number | null;
            month: number | null;
            year: number;
        } | null;
        journalPublishDate: Date | null;
        journalPublishSplitDate: {
            day: number | null;
            month: number | null;
            year: number;
        } | null;
    };
    params: {
        language: "fr-Fr" | "en-US";
    };
    response: {
        code: 200;
        information: "document.upsert";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
