// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type ArticleType = "adaptiveClinicalTrial" | "address" | "autobiography" | "bibliography" | "biography" | "booksAndDocuments" | "caseReports" | "classicalArticle" | "clinicalConference" | "clinicalStudy" | "clinicalTrial" | "clinicalTrialProtocol" | "clinicalTrialPhaseI" | "clinicalTrialPhaseII" | "clinicalTrialPhaseIII" | "clinicalTrialPhaseIV" | "clinicalTrialVeterinary" | "collectedWork" | "comment" | "comparativeStudy" | "congress" | "consensusDevelopmentConference" | "consensusDevelopmentConferenceNIH" | "controlledClinicalTrial" | "correctedAndRepublishedArticle" | "dataset" | "dictionary" | "directory" | "duplicatePublication" | "editorial" | "electronicSupplementaryMaterials" | "englishAbstract" | "equivalenceTrial" | "evaluationStudy" | "expressionOfConcern" | "festschrift" | "governmentPublication" | "guideline" | "historicalArticle" | "interactiveTutorial" | "interview" | "introductoryJournalArticle" | "journalArticle" | "lecture" | "legalCase" | "legislation" | "letter" | "metaAnalysis" | "multicenterStudy" | "news" | "newspaperArticle" | "observationalStudy" | "observationalStudyVeterinary" | "overall" | "patientEducationHandout" | "periodicalIndex" | "personalNarrative" | "portrait" | "practiceGuideline" | "pragmaticClinicalTrial" | "preprint" | "publishedErratum" | "randomizedControlledTrial" | "randomizedControlledTrialVeterinary" | "researchSupportAmericanRecoveryAndReinvestmentAct" | "researchSupportNIHExtramural" | "researchSupportNIHIntramural" | "researchSupportNonUSGovt" | "researchSupportUSGovtNonPHS" | "researchSupportUSGovtPHS" | "researchSupportUSGovt" | "retractedPublication" | "retractionOfPublication" | "review" | "scopingReview" | "scientificIntegrityReview" | "systematicReview" | "technicalReport" | "twinStudy" | "validationStudy" | "videoAudioMedia" | "webcast";

export { ArticleType };

type Language = "fr-FR" | "en-US";

export { Language };

type CodegenRoutes = ({
    method: "PUT";
    path: "/document/{language}";
    body: {
        abysBakedDocumentId: string;
        title: string;
        articleTypes: ArticleType[];
        authors: string[];
        summary: string | null;
        abstract: string | null;
        providers: ("pubmed")[];
        keywords: string[];
        webPublishDate: Date | null;
        webPublishSplitDate: {
            day: number | null;
            month: number | null;
            year: number;
        } | null;
        journalPublishDate: Date | null;
        journalPublishSplitDate: {
            day: number | null;
            month: number | null;
            year: number;
        } | null;
    };
    params: {
        language: Language;
    };
    response: {
        code: 200;
        information: "document.upsert";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/simple-search-result";
    body: {
        language: Language;
        page: number;
        quantityPerPage: number;
        term: string;
        filtersValues?: {
            articleType?: ArticleType[] | undefined;
        } | undefined;
    };
    response: {
        code: 200;
        information: "simpleSearch.results";
        body: {
            score: number;
            abysBakedDocumentId: string;
            title: string;
            articleType: ArticleType[];
            authors: string[];
            webPublishDate: string | null;
            journalPublishDate: string | null;
            summary: string | null;
            keywords: string[] | null;
        }[];
    };
}) | ({
    method: "POST";
    path: "/facets";
    body: {
        language: Language;
        term: string;
        filtersValues?: {
            articleType?: ArticleType[] | undefined;
        } | undefined;
    };
    response: {
        code: 200;
        information: "facets.result";
        body: {
            total: number;
            facets: ({
                name: "articleType";
                values: {
                    value: ArticleType;
                    quantity: number;
                }[];
            } | {
                name: "year";
                values: {
                    value: number;
                    quantity: number;
                }[];
            } | {
                name: "gender";
                values: {
                    value: "male" | "female";
                    quantity: number;
                }[];
            } | {
                name: "species";
                values: {
                    value: "human" | "otherAnimal";
                    quantity: number;
                }[];
            })[];
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
