services:
  abys:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/abys run duplo:dev
    depends_on:
      - abys-mongo
      - abys-mongo-viewer
  abys-mongo:
    extends:
      file: ${TEMPLATE_COMPOSE_MONGO_DEV}
      service: template-mongo
    env_file: ${INCLUDE_PATH}/abys/.env
    volumes:
      - "abys-mongo-data:/data/db"
    attach: false
  abys-mongo-viewer:
    image: mongo-express
    ports:
      - 55553:1506
    env_file: ${INCLUDE_PATH}/abys/.env
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_DATABASE_URL}
    depends_on:
      - abys-mongo
    attach: false

volumes:
  abys-mongo-data:
