services:
  spotter:
    image: 'ghcr.io/${{ github.repository_owner }}/seaence_spotter:${TAG}'
    command: npm -w services/spotter run dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - published: 7000
        target: 80