include:
  # installer node global
  - path:
      - ./.docker/node-installer.compose.yml
  # spotter service (client front)
  - path:
      - ${INCLUDE_PATH}/spotter/compose.yml
  # rosetta service (libre translate)
  - path:
      - ${INCLUDE_PATH}/rosetta/compose.yml
  # sea service (elastic search)
  - path:
      - ${INCLUDE_PATH}/sea/compose.yml
  # school service
  - path:
      - ${INCLUDE_PATH}/school/compose.yml
  # pilot service (BO school)
  - path:
      - ${INCLUDE_PATH}/pilot/compose.yml
  # marine-snow service
  - path:
      - ${INCLUDE_PATH}/marine-snow/compose.yml
  # tide service (BO marine-snow)
  - path:
      - ${INCLUDE_PATH}/tide/compose.yml
  # horizon service (gateway)
  - path:
      - ${INCLUDE_PATH}/horizon/compose.yml
  # harbor service (auth)
  - path:
      - ${INCLUDE_PATH}/harbor/compose.yml
  # abys service
  - path:
      - ${INCLUDE_PATH}/abys/compose.yml
  # colossal service (BO abys)
  - path:
      - ${INCLUDE_PATH}/colossal/compose.yml
  # bottle service (notification)
  - path:
      - ${INCLUDE_PATH}/bottle/compose.yml
