services:
  spotter:
    image: 'ghcr.io/mathcovax/seaence_spotter:${TAG}'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - published: 7000
        target: 80