services:
  sea-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    env_file:
      - ${INCLUDE_PATH}/sea/.env
    ports:
      - 9200:9200
    attach: false
    volumes:
      - sea-es-data:/usr/share/elasticsearch/data
  sea:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    ports:
      - 9300:1506
    command: npm -w services/sea run duplo:dev
    depends_on:
      - sea-es

volumes:
  sea-es-data:
