services:
  sea:
    image: elasticsearch:8.17.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - sea-es-data:/usr/share/elasticsearch/data
volumes:
  sea-es-data:
