services:
  sea-es:
    extends:
      file: ${INCLUDE_PATH}/sea/compose.template.yml
      service: sea-es-template
    ports:
      - 9200:9200
  kibana:
    extends:
      file: ${INCLUDE_PATH}/sea/compose.template.yml
      service: kibana-template
    ports:
      - 5601:5601
  sea:
    extends:
      file: ${INCLUDE_PATH}/sea/compose.template.yml
      service: sea-duplo-template
    command: npm -w services/sea run duplo:dev

networks:
  elastic:
    driver: bridge
volumes:
  sea-es-data:
