services:
  sea-es:
    extends:
      file: ${INCLUDE_PATH}/sea/compose.template.yml
      service: sea-es-template
    ports:
      - 9200:9200
    attach: false
  # kibana:
  #   extends:
  #     file: ${INCLUDE_PATH}/sea/compose.template.yml
  #     service: kibana-template
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - sea-es
  #   attach: false
  sea:
    extends:
      file: ${INCLUDE_PATH}/sea/compose.template.yml
      service: sea-duplo-template
    ports:
      - 9300:1506
    command: npm -w services/sea run duplo:dev
    depends_on:
      - sea-es

volumes:
  sea-es-data:
