services:
  sea-es:
    image: elasticsearch:8.17.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - sea-es-data:/usr/share/elasticsearch/data
  sea:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/sea run dev
volumes:
  sea-es-data:
