services:
  sea-es-template:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0 # 8.17.0
    #platform: linux/arm64/v8
    env_file:
      - ${INCLUDE_PATH}/sea/.env
    volumes:
      - sea-es-data:/usr/share/elasticsearch/data
  kibana-template:
    image: docker.elastic.co/kibana/kibana:8.18.0 # 8.17.0
    env_file:
      - ${INCLUDE_PATH}/sea/.env
    environment:
      ELASTICSEARCH_HOSTS: ${ES_BASE_URL}
    depends_on:
      - sea-es
  sea-duplo-template:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/sea run dev
    depends_on:
      - sea-es
