services:
  sea-es-template:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3 # 8.17.0
    #platform: linux/arm64/v8
    env_file:
      - ${INCLUDE_PATH}/sea/.env
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 1GB
    volumes:
      - sea-es-data:/usr/share/elasticsearch/data
  kibana-template:
    image: docker.elastic.co/kibana/kibana:8.17.3 # 8.17.0
    networks:
      - elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://sea-es:9200
    depends_on:
      - sea-es
  sea-duplo-template:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/sea run dev
