// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/upsert-baked-document-translation-reporting";
    body: {
        userId: string;
        bakedDocumentId: string;
        reportingDetails: string;
    };
    response: {
        code: 204;
        information: "bakedDocumentTranslationReporting.upsert";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
