// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/upsert-baked-document-translation-reporting";
    body: {
        userId: string;
        bakedDocumentId: string;
        reportingDetails: string;
    };
    response: {
        code: 204;
        information: "bakedDocumentTranslationReporting.upsert";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/find-many-baked-document-translation-reporting/{bakedDocumentId}";
    body: {
        quantityPerPage: number;
        page: number;
    };
    params: {
        bakedDocumentId: string;
    };
    response: {
        code: 200;
        information: "bakedDocumentTranslationReporting.findMany";
        body: {
            bakedDocumentId: string;
            userId: string;
            id: string;
            details: string;
        }[];
    };
}) | ({
    method: "POST";
    path: "/find-many-baked-document-translation-reporting-details/{bakedDocumentId}";
    params: {
        bakedDocumentId: string;
    };
    response: {
        code: 200;
        information: "bakedDocumentTranslationReporting.findManyDetails";
        body: {
            countTotal: number;
        };
    };
}) | ({
    method: "POST";
    path: "/find-many-baked-document-translation-reporting-aggregate";
    body: {
        quantityPerPage: number;
        page: number;
    };
    response: {
        code: 200;
        information: "bakedDocumentTranslationReportingAggregate.findMany";
        body: {
            bakedDocumentId: string;
            reportingQuantity: number;
        }[];
    };
}) | ({
    method: "POST";
    path: "/find-many-baked-document-translation-reporting-aggregate-details";
    response: {
        code: 200;
        information: "bakedDocumentTranslationReportingAggregate.findManyDetails";
        body: {
            countTotal: number;
        };
    };
}) | ({
    method: "POST";
    path: "/baked-document-translation-reporting-aggregate/process/{bakedDocumentId}";
    body: {
        cookingMode: "default" | "googleScrape" | "libretranslate";
        nodeSameRawDocumentId: string;
        bakedDocumentLanguage: "fr-FR" | "en-US";
    };
    params: {
        bakedDocumentId: string;
    };
    response: {
        code: 404;
        information: "bakedDocumentTranslationReportingAggregate.notfound";
        body?: undefined;
    } | {
        code: 204;
        information: "bakedDocumentTranslationReportingAggregate.processed";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
