import {
	mdiMenu,
	mdiClose,
	mdiViewGrid,
	mdiFormatListBulletedSquare,
	mdiPlus,
	mdiAccount,
	mdiCalendarMonth,
	mdiFileDocument,
	mdiTag,
	mdiStarOutline,
	mdiStar,
	mdiMessageText,
	mdiMagnify,
	mdiMagnifyPlus,
	mdiWeb,
	mdiLogin,
	mdiForum,
	mdiArrowLeft,
	mdiSend,
	mdiLinkVariant,
	mdiBellOutline,
	mdiBell,
	mdiMessageOutline,
	mdiCheck,
	mdiClock,
	mdiPost,
	mdiHome,
	mdiIdentifier,
	mdiAlert,
	mdiAlertCircle,
	mdiWeight,
	mdiSitemap,
	mdiTranslate,
	mdiTextBox,
	mdiListBox,
	mdiHeart,
	mdiContentSave,
	mdiFolder,
	mdiFolderOutline,
	mdiDotsHorizontal,
	mdiDotsVertical,
	mdiDotsHorizontalCircle,
	mdiDotsHorizontalCircleOutline,
	mdiDeleteOutline,
	mdiDelete,
	mdiFileOutline,
	mdiFile,
	mdiChevronDown,
	mdiChefHat,
	mdiFolderFileOutline,
	mdiReply,
} from "@mdi/js";

export const iconsMapper = {
	close: mdiClose,
	menu: mdiMenu,
	viewGrid: mdiViewGrid,
	formatListBulletedSquare: mdiFormatListBulletedSquare,
	plus: mdiPlus,
	calendar: mdiCalendarMonth,
	document: mdiFileDocument,
	tag: mdiTag,
	account: mdiAccount,
	starOutline: mdiStarOutline,
	star: mdiStar,
	messageText: mdiMessageText,
	magnify: mdiMagnify,
	magnifyPlus: mdiMagnifyPlus,
	web: mdiWeb,
	login: mdiLogin,
	forum: mdiForum,
	arrowLeft: mdiArrowLeft,
	send: mdiSend,
	linkVariant: mdiLinkVariant,
	bell: mdiBell,
	bellOutline: mdiBellOutline,
	messageOutline: mdiMessageOutline,
	check: mdiCheck,
	clock: mdiClock,
	post: mdiPost,
	answer: mdiReply,
	home: mdiHome,
	identifier: mdiIdentifier,
	alert: mdiAlert,
	reporting: mdiAlertCircle,
	weight: mdiWeight,
	sitemap: mdiSitemap,
	translate: mdiTranslate,
	textBox: mdiTextBox,
	listBox: mdiListBox,
	heart: mdiHeart,
	contentSave: mdiContentSave,
	folder: mdiFolder,
	folderOutline: mdiFolderOutline,
	dotsHorizontal: mdiDotsHorizontal,
	dotsVertical: mdiDotsVertical,
	dotsHorizontalCircle: mdiDotsHorizontalCircle,
	dotsHorizontalCircleOutline: mdiDotsHorizontalCircleOutline,
	delete: mdiDelete,
	deleteOutline: mdiDeleteOutline,
	file: mdiFile,
	fileOutline: mdiFileOutline,
	chevronDown: mdiChevronDown,
	chefHat: mdiChefHat,
	folderFileOutline: mdiFolderFileOutline,
};

export const iconSizeMapper = {
	small: 14,
	default: 24,
	large: 36,
};
