import {
	mdiMenu,
	mdiClose,
	mdiViewGrid,
	mdiFormatListBulletedSquare,
	mdiPlus,
	mdiAccount,
	mdiCalendarMonth,
	mdiFileDocument,
	mdiTag,
	mdiStarOutline,
	mdiStar,
	mdiMessageText,
	mdiMagnify,
	mdiMagnifyPlus,
	mdiWeb,
	mdiLogin,
	mdiForum,
	mdiArrowLeft,
	mdiSend,
	mdiLinkVariant,
	mdiBellOutline,
	mdiBell,
	mdiMessageOutline,
	mdiCheck,
	mdiClock,
	mdiPost,
	mdiHome,
	mdiIdentifier,
	mdiAlert,
	mdiAlertCircle,
	mdiWeight,
	mdiSitemap,
	mdiTranslate,
	mdiTextBox,
	mdiListBox,
	mdiHeart,
	mdiContentSaveCheck,
	mdiChefHat,
} from "@mdi/js";

export const iconsMapper = {
	close: mdiClose,
	menu: mdiMenu,
	viewGrid: mdiViewGrid,
	formatListBulletedSquare: mdiFormatListBulletedSquare,
	plus: mdiPlus,
	calendar: mdiCalendarMonth,
	document: mdiFileDocument,
	tag: mdiTag,
	account: mdiAccount,
	starOutline: mdiStarOutline,
	star: mdiStar,
	messageText: mdiMessageText,
	magnify: mdiMagnify,
	magnifyPlus: mdiMagnifyPlus,
	web: mdiWeb,
	login: mdiLogin,
	forum: mdiForum,
	arrowLeft: mdiArrowLeft,
	send: mdiSend,
	linkVariant: mdiLinkVariant,
	bell: mdiBell,
	bellOutline: mdiBellOutline,
	messageOutline: mdiMessageOutline,
	check: mdiCheck,
	clock: mdiClock,
	post: mdiPost,
	home: mdiHome,
	identifier: mdiIdentifier,
	alert: mdiAlert,
	reporting: mdiAlertCircle,
	weight: mdiWeight,
	sitemap: mdiSitemap,
	translate: mdiTranslate,
	textBox: mdiTextBox,
	listBox: mdiListBox,
	heart: mdiHeart,
	contentSaveCheck: mdiContentSaveCheck,
	chefHat: mdiChefHat,
};

export const iconSizeMapper = {
	small: 14,
	default: 24,
	large: 36,
};
