export * from "./comparator/articleType";
export * from "./comparator/author";
export * from "./comparator/provider";
export * from "./comparator/strictText";
export * from "./comparator/text";
export * from "./comparator/year";
export * from "./comparator/yearInterval";
export * from "./comparator";
export * from "./operator";
