import "../repositories";
import { AddEquationInFavoriUsecase } from "@business/applications/usecases/addEquationInFavori";
import { ComputeDocumentQuantityInFolderrUsecase } from "@business/applications/usecases/computeDocumentQuantityInFolder";
import { CreateDocumentInFolderUsecase } from "@business/applications/usecases/createDocumentInFolder";
import { RemoveDocumentInFolderUsecase } from "@business/applications/usecases/removeDocumentInFolder";
import { RemoveDocumentFolderUsecase } from "@business/applications/usecases/removeDocumentFolder";
import { RemoveEquationInFavoriUsecase } from "@business/applications/usecases/removeEquationInfavori";
import { CreateDocumentFolderUsecase } from "@business/applications/usecases/createDocumentFolder";
import { FindDocumentInFolderUsecase } from "@business/applications/usecases/findDocumentInFolder";
import { FindEquationInFavoriByIdUsecase } from "@business/applications/usecases/findEquationInFavoriById";
import { UpdateDocumentInFoldersUsecase } from "@business/applications/usecases/updateDocumentInFolders";
import { FindDocumentFolderByIdUsecase } from "@business/applications/usecases/findDocumentFolderById";

export const addEquationInFavoriUsecase = new AddEquationInFavoriUsecase();
export const computeDocumentQuantityInFolderrUsecase = new ComputeDocumentQuantityInFolderrUsecase();
export const createDocumentInFolderUsecase = new CreateDocumentInFolderUsecase();
export const removeDocumentInFolderUsecase = new RemoveDocumentInFolderUsecase();
export const removeDocumentFolderUsecase = new RemoveDocumentFolderUsecase();
export const removeEquationInFavoriUsecase = new RemoveEquationInFavoriUsecase();
export const createDocumentFolderUsecase = new CreateDocumentFolderUsecase();
export const findDocumentInFolderUsecase = new FindDocumentInFolderUsecase();
export const findEquationInFavoriByIdUsecase = new FindEquationInFavoriByIdUsecase();
export const updateDocumentInFoldersUsecase = new UpdateDocumentInFoldersUsecase();
export const findDocumentFolderByIdUsecase = new FindDocumentFolderByIdUsecase();
