// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/create-register-notification";
    body: {
        id: string;
        username: string;
        email: string;
        language: "fr-FR" | "en-US";
    };
    response: {
        code: 200;
        information: "notification.sent";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
