// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/enable-reply-post-notification-setting";
    body: {
        userId: string;
        postId: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "replyPostNotification.enable";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/disable-reply-post-notification-setting";
    body: {
        userId: string;
        postId: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 404;
        information: "replyToPostNotificationSetting.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "replyPostNotification.disable";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/find-reply-to-post-notification-setting";
    body: {
        userId: string;
        postId: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 404;
        information: "replyToPostNotificationSetting.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "replyPostNotificationSetting.found";
        body: {
            user: {
                id: string;
                username: string;
                email: string;
                language: "fr-FR" | "en-US";
            };
            postId: string;
            type: "replyToPostNotificationSettingType";
        } | null;
    };
}) | ({
    method: "POST";
    path: "/find-notifications";
    body: {
        userId: string;
        page: number;
        quantityPerPage: number;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "notifications.found";
        body: ({
            id: string;
            user: {
                id: string;
                username: string;
                email: string;
                language: "fr-FR" | "en-US";
            };
            processed: boolean;
            createdAt: Date;
            deleteAt: Date;
            type: "registerNotificationType";
        } | {
            id: string;
            user: {
                id: string;
                username: string;
                email: string;
                language: "fr-FR" | "en-US";
            };
            processed: boolean;
            createdAt: Date;
            deleteAt: Date;
            postId: string;
            usernameOfReplyPost: string;
            summaryOfReplyPost: string;
            type: "replyToPostNotificationType";
        } | {
            id: string;
            user: {
                id: string;
                username: string;
                email: string;
                language: "fr-FR" | "en-US";
            };
            processed: boolean;
            createdAt: Date;
            deleteAt: Date;
            type: "userPostBanNotificationType";
            postId: string;
            reason: string;
            warningId: string;
        } | {
            id: string;
            user: {
                id: string;
                username: string;
                email: string;
                language: "fr-FR" | "en-US";
            };
            processed: boolean;
            createdAt: Date;
            deleteAt: Date;
            type: "userPostWarningNotificationType";
            postId: string;
            reason: string;
            warningId: string;
        })[];
    };
}) | ({
    method: "POST";
    path: "/count-notifications";
    body: {
        userId: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "notifications.count";
        body: {
            count: number;
        };
    };
}) | ({
    method: "POST";
    path: "/create-post-warning-notification";
    body: {
        userId: string;
        warningId: string;
        postId: string;
        reason: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 201;
        information: "notification.postWarning.created";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/create-post-ban-notification";
    body: {
        userId: string;
        warningId: string;
        postId: string;
        reason: string;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 201;
        information: "notification.postBan.created";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
