// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/send-registration-email";
    body: {
        userId: string;
        userEmail: string;
        username: string;
    };
    response: {
        code: 200;
        information: "notification.sent";
        body?: undefined;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
