const sectionEnumSchema = zod.enum([
	"abstract",
	"expect",
	"conflictOfInterestStatement",
	"figures",
	"commentIn",
	"similarArticles",
	"citedBy",
	"references",
	"publicationTypes",
	"meshTerms",
	"substances",
	"associatedData",
	"relatedInformation",
	"linkOutMoreResources",
]);
