services:
  bottle:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/bottle run dev
    depends_on:
      - bottle-mongo
      - maildev
      - async-message-mongo
  bottle-mongo:
    extends:
      file: ${TEMPLATE_COMPOSE_MONGO_DEV}
      service: template-mongo
    env_file: ${INCLUDE_PATH}/bottle/.env
    volumes:
      - "bottle-mongo-data:/data/db"
  bottle-mongo-viewer:
    image: mongo-express
    ports:
      - 55555:1506
    env_file: ${INCLUDE_PATH}/bottle/.env
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_DATABASE_URL}
    depends_on:
      - bottle-mongo
    attach: false
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  bottle-mongo-data:
