import { createEnum, type GetEnumValue } from "@vendors/clean";

export const abstractSectionNameEnum = createEnum([
	"introduction",
	"background",
	"objective",
	"method",
	"result",
	"conclusion",
	"reference",
	"acknowledgment",
	"objective",
	"option",
	"outcome",
	"evidence",
	"value",
	"benefit",
	"recommendation",
	"validation",
	"sponsor",
	"purpose",
	"patient",
	"setting",
	"studyObjective",
	"measurementAndMainResult",

	"introductions",
	"backgrounds",
	"objectives",
	"methods",
	"results",
	"conclusions",
	"references",
	"acknowledgments",
	"objectives",
	"options",
	"outcomes",
	"evidences",
	"values",
	"benefits",
	"recommendations",
	"validations",
	"sponsors",
	"purposes",
	"patients",
	"settings",
	"studyObjectives",
	"measurementsAndMainResults",
]);

export type AbstractSectionName = GetEnumValue<typeof abstractSectionNameEnum>;
