services:
  template-node:
    image: node:22.14
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully