// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/translate";
    body: {
        provider: "default" | "googleScrape" | "libretranslate";
        language: "fr-FR" | "en-US";
        text: string;
    };
    response: {
        code: 200;
        information: "text.translated";
        body: string;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
