// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type OperatorContent = OperatorAnd | OperatorOR | OperatorNot | ComparatorText | ComparatorYear;

export { OperatorContent };

type OperatorAnd = {
    type: "operator";
    name: "and";
    content: OperatorContent[];
};

export { OperatorAnd };

type OperatorOR = {
    type: "operator";
    name: "or";
    content: OperatorContent[];
};

export { OperatorOR };

type OperatorNot = {
    type: "operator";
    name: "not";
    content: OperatorContent | null;
};

export { OperatorNot };

type ComparatorText = {
    type: "comparator";
    name: "text";
    field: "allField" | "title" | "abstract";
    value: string;
};

export { ComparatorText };

type ComparatorYear = {
    type: "comparator";
    name: "year";
    field: "allDate" | "webDate" | "journalDate";
    value: number;
};

export { ComparatorYear };

type CodegenRoutes = ({
    method: "POST";
    path: "/create-document-folder";
    body: {
        userId: string;
        title: string;
    };
    response: {
        code: 200;
        information: "documentFolder.created";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/get-document-folder";
    body: {
        userId: string;
        documentFolderId: string;
    };
    response: {
        code: 200;
        information: "documentFolder.found";
        body: {
            id: string;
            userId: string;
            title: string;
            numberOfDocument: number;
            createdAt: Date;
        };
    };
}) | ({
    method: "POST";
    path: "/remove-document-folder";
    body: {
        userId: string;
        documentFolderId: string;
    };
    response: {
        code: 200;
        information: "documentFolder.removed";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/search-document-folders-per-page";
    body: {
        userId: string;
        partialTitleDocumentFolder: string;
        page: number;
        quantityPerPage: number;
    };
    response: {
        code: 200;
        information: "documentFolders.found";
        body: {
            id: string;
            userId: string;
            title: string;
            numberOfDocument: number;
            createdAt: Date;
        }[];
    };
}) | ({
    method: "POST";
    path: "/get-search-document-folders-count";
    body: {
        userId: string;
        partialTitleDocumentFolder: string;
    };
    response: {
        code: 200;
        information: "documentFolders.searchDetails";
        body: number;
    };
}) | ({
    method: "POST";
    path: "/add-document-in-folder";
    body: {
        userId: string;
        documentFolderId: string;
    } & {
        nodeSameRawDocumentId: string;
        documentInFolderName: string;
    };
    response: {
        code: 200;
        information: "documentInFolder.added";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/get-document-in-folder";
    body: {
        userId: string;
        documentFolderId: string;
    } & {
        nodeSameRawDocumentId: string;
    };
    response: {
        code: 200;
        information: "documentInFolder.found";
        body: {
            documentFolderId: string;
            nodeSameRawDocumentId: string;
            name: string;
            addedAt: Date;
        };
    };
}) | ({
    method: "POST";
    path: "/remove-document-in-folder";
    body: {
        userId: string;
        documentFolderId: string;
    } & {
        nodeSameRawDocumentId: string;
    };
    response: {
        code: 200;
        information: "documentInFolder.removed";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/search-documents-in-folder";
    body: {
        userId: string;
        documentFolderId: string;
    } & {
        partialNameDocument: string;
        page: number;
        quantityPerPage: number;
    };
    response: {
        code: 200;
        information: "documentsInFolder.found";
        body: {
            documentFolderId: string;
            nodeSameRawDocumentId: string;
            name: string;
            addedAt: Date;
        }[];
    };
}) | ({
    method: "POST";
    path: "/get-search-documents-in-folder-count";
    body: {
        userId: string;
        documentFolderId: string;
    } & {
        partialNameDocument: string;
    };
    response: {
        code: 200;
        information: "documentsInFolder.searchDetails";
        body: number;
    };
}) | ({
    method: "POST";
    path: "/add-equation-to-favorite";
    body: {
        userId: string;
        equation: OperatorContent;
        equationName: string;
    };
    response: {
        code: 200;
        information: "eqaution.added-to-favorite";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/get-favorite-equation";
    body: {
        userId: string;
        favoriEquationId: string;
    };
    response: {
        code: 200;
        information: "favoriEquation.found";
        body: {
            id: string;
            name: string;
            userId: string;
            equation: OperatorContent;
            addedAt: Date;
        };
    };
}) | ({
    method: "POST";
    path: "/remove-equation-from-favorite";
    body: {
        userId: string;
        favoriEquationId: string;
    };
    response: {
        code: 200;
        information: "favoriequation.removed";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/search-favori-equations";
    body: {
        userId: string;
        partialNameFavoriEquation: string;
        page: number;
        quantityPerPage: number;
    };
    response: {
        code: 200;
        information: "favoriEquations.found";
        body: {
            id: string;
            name: string;
            userId: string;
            equation: OperatorContent;
            addedAt: Date;
        }[];
    };
}) | ({
    method: "POST";
    path: "/get-search-favori-equations-count";
    body: {
        userId: string;
        partialNameFavoriEquation: string;
    };
    response: {
        code: 200;
        information: "favoriEquations.searchDetails";
        body: number;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
