// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/create-warning";
    body: {
        type: "post";
        makeUserBan: boolean;
        reason: string;
        postId: string;
    } | never;
    response: {
        code: 200;
        information: "warning.created";
        body: {
            id: string;
            makeUserBan: boolean;
            reason: string;
        } | {
            id: string;
            makeUserBan: boolean;
            reason: string;
            postId: string;
        };
    };
}) | ({
    method: "POST";
    path: "/create-warning";
    body: {
        type: "post";
        makeUserBan: boolean;
        reason: string;
        postId: string;
    } | never;
    response: {
        code: 200;
        information: "warning.created";
        body: {
            id: string;
            makeUserBan: boolean;
            reason: string;
        } | {
            id: string;
            makeUserBan: boolean;
            reason: string;
            postId: string;
        };
    };
}) | ({
    method: "POST";
    path: "/find-user";
    body: {
        accessToken: string;
    };
    response: {
        code: 401;
        information: "accessToken.invalid";
        body?: undefined;
    } | {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "user.found";
        body: {
            id: string;
            email: string;
            username: string;
            lastUpdate: Date;
        };
    };
}) | ({
    method: "POST";
    path: "/update-user";
    body: {
        userId: string;
        username?: string | undefined;
    };
    response: {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 403;
        information: "user.shortUpdatedDelay";
        body?: undefined;
    } | {
        code: 204;
        information: "user.updated";
        body?: undefined;
    };
}) | ({
    method: "POST";
    path: "/login";
    body: {
        firebaseToken: string;
    };
    response: {
        code: 401;
        information: "firebase.token.invalid";
        body?: undefined;
    } | {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "user.logged";
        body: {
            accessToken: string;
        };
    };
}) | ({
    method: "POST";
    path: "/register";
    body: {
        firebaseToken: string;
        username: string;
    };
    response: {
        code: 401;
        information: "firebase.token.invalid";
        body?: undefined;
    } | {
        code: 409;
        information: "user.emailAlreadyExist";
        body?: undefined;
    } | {
        code: 200;
        information: "user.registered";
        body: {
            accessToken: string;
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
