// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/authentication";
    body: string;
    response: {
        code: 401;
        information: "firebase.token.invalid";
        body?: undefined;
    } | {
        code: 200;
        information: "user.logged";
        body: string;
    };
}) | ({
    method: "POST";
    path: "/user";
    body: string;
    response: {
        code: 401;
        information: "access.token.invalid";
        body?: undefined;
    } | {
        code: 404;
        information: "user.notfound";
        body?: undefined;
    } | {
        code: 200;
        information: "user.found";
        body: {
            id: string;
            email: string;
            username: string;
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
