// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
interface CodegenReceiveFormData<GenericValue extends Record<string, string | string[] | number | number[] | Date | Date[] | File[]>> {
    extractor: (...args: any[]) => Promise<GenericValue>;
}

export { CodegenReceiveFormData };

type CodegenRoutes = ({
	method: "POST";
	path: "/detect";
	body: CodegenReceiveFormData<{
		q: string;
		api_key?: string;
	}>;
	response: {
		code: 200;
		information: undefined;
		body: {
			confidence: number;
			language: "fr" | "en" | "it" | "es" | string;
		}[];
	} | {
		code: 400 | 403 | 429 | 500;
		information: undefined;
		body: {
			error: string;
		};
	};
}) | ({
	method: "GET";
	path: "/languages";
	response: {
		code: 200;
		information: undefined;
		body: {
			code: string;
			name: string;
			targets: string[];
		}[];
	}
}) | ({
	method: "POST";
	path: "/translate";
	body: CodegenReceiveFormData<{
		q: string;
		source: "auto" | "fr" | "it" | "en" | "es";
		target: "fr" | "it" | "en" | "es";
		format: "text" | "html";
		alternatives?: number;
		api_key?: string;
	}>;
	response: {
		code: 200;
		information: undefined;
		body: {
			alternatives?: string[];
			detectedLanguage?: {
				confidence: number;
				language: "fr" | "it" | "en" | "es";
			};
			translatedText: string;
		};
	} | {
		code: 400 | 403 | 429 | 500;
		information: undefined;
		body: {
			error: string;
		};
	};
}) | ({
	method: "GET";
	path: "/frontend/settings";	
	response: {
		code: 200;
		information: undefined;
		body: {
			apyKeys: boolean;
			charLimit: number;
			filesTranslation: boolean;
			frontendTimeout: number;
			keyRequired: boolean;
			language: {
				source: {
					code: "auto" | "fr" | "it" | "en" | "es";
					name: string;
				};
				target: {
					code: "fr" | "it" | "en" | "es";
					name: string;
				};
			};
			suggestions: boolean;
			supportedFilesFormat: (".txt" | ".odt" | ".odp" | ".docx" | ".pptx" | ".epub" | ".html")[];
		}
	}
}) | ({
	method: "POST";
	path: "/suggest";
	body: CodegenReceiveFormData<{
		q: string;
		s: string;
		source: "auto" | "fr" | "it" | "en" | "es";
		target: "fr" | "it" | "en" | "es";
	}>;
	response: {
		code: 200;
		information: undefined;
		body: {
			success: true;
		};
	} | {
		code: 400;
		information: undefined;
		body: {
			error: string;
		};
	};
});

export { CodegenRoutes };
/* v8 ignore stop */
