services:
  school:
    extends:
      file: ${TEMPLATE_COMPOSE_NODE_DEV}
      service: template-node
    command: npm -w services/school run duplo:dev
    ports:
      - "1506:1506"
    depends_on:
      - school-mongo
  school-mongo:
    extends:
      file: ${TEMPLATE_COMPOSE_MONGO_DEV}
      service: template-mongo
    env_file: ${INCLUDE_PATH}/school/.env
    ports:
      - "27005:27017"
    volumes:
      - "school-mongo-data:/data/db"
  school-mongo-viewer:
    image: mongo-express
    ports:
      - 55554:1506
    env_file: ${INCLUDE_PATH}/school/.env
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_DATABASE_URL}
    depends_on:
      - school-mongo
    attach: false
volumes:
  school-mongo-data:
